import Head from "next/head";
import { MainLayout } from "@/components/layouts/MainLayout";
import useGetAccountInformation from "@/utils/useGetAccountInfo";
import useIsAuthenticated from "@/utils/useIsAuthenticated";

export default function Home() {
  const isAuthenticated = useIsAuthenticated();
  const acc = useGetAccountInformation();

  let content;
  if (isAuthenticated) {
    content = `Welcome back @${acc.username}!`;
  } else {
    content = "User is not logged in";
  }

  return (
    <>
      <Head>
        <title>Card Simulator</title>
        <meta name="description" content="Generated by create-t3-app" />
        <meta name="author" content="Brandon Ongtingco and Quyen Huynh" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>{content}</MainLayout>
    </>
  );
}
